# Site settings
title: "Best Practices, Content Strategy and Technology for B2B Blogs"
email: "mike@beegit.com"
description: "Regular insight about content strategy, Markdown and writing technology to help B2B content teams generate and convert leads."
baseurl: ""
url: "http://blog.beegit.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
permalink: pretty

gems:
  - jekyll-redirect-from
  - jekyll-redirect-to
